export const imageUrls = {
  mainTime: 'game_time',
  mainScore: 'goal',
  mainTeams: 'searchBar',
  mainHomeOdds: 'homeOdds',
  mainAwayOdds: 'awayOdds',
  mainDrawOdds: 'drawOdds',
  mainSonT: 'shots_on',
  mainSoffT: 'shots_off',
  mainAttacks: 'attack',
  mainDangerousAttacks: 'd_attack',
  mainAttackConversion: 'conversion',
  mainCorners: 'corner',
  mainPossession: 'possession',
  mainRedCards: 'red_card',
  mainYellowCards: 'yellow_card',
  mainGraph1: 'chart1',
  mainGraph2: 'chart2',
  previousSonT: 'shots_on',
  previousSoffT: 'shots_off',
  previousAttacks: 'attack',
  previousDangerousAttacks: 'd_attack',
  previousCorners: 'corner',
  previousGoals: 'goal',
  previousIntensity: 'pressure',
  miscMomentum: 'momentum',
  miscFavourites: 'bell',
  miscDelete: 'trash'
};


// export const fieldNames = [
//   { text: 'Goal', value: 'Goals' },
//   { text: 'Red Card', value: 'RedCards' },
//   { text: 'Yellow Card', value: 'YellowCards' },
//   { text: 'Shots on Target', value: 'ShotsOnTarget' },
//   { text: 'Shots off Target', value: 'ShotsOffTarget' },
//   { text: 'Corner', value: 'Corners' },
// ];

export const fieldNames = [
  // { text: // 'Time',value:''},
  { text: 'Home Shots on Target',value:'homeShotsOnTarget'},
  { text: 'Home Shots off Target',value:'homeShotsOffTarget'},
  { text: 'Home Attacks',value:'homeAttacks'},
  { text: 'Home Dangerous Attacks',value:'homeDangerousAttacks'},
  { text: 'Home Corners',value:'homeCorners'},
  // { text: // 'Home Possession',value:''},
  { text: 'Home Yellow Cards',value:'homeYellowCards'},
  { text: 'Home Red Cards',value:'homeRedCards '},
  { text: 'Home Goals',value:'homeGoals'},
  { text: 'Away Shots on Target',value:'awayShotsOnTarget'},
  { text: 'Away Shots off Target',value:'awayShotsOffTarget'},
  { text: 'Away Attacks',value:'awayAttacks'},
  { text: 'Away Dangerous Attacks',value:'awayDangerousAttacks'},
  { text: 'Away Corners',value:'awayCorners'},
  // { text: // 'Away Possession',value:''},
  { text: 'Away Yellow Cards',value:'awayYellowCards'},
  { text: 'Away Red Cards',value:'awayRedCards'},
  { text: 'Away Goals',value:'awayGoals'},
//   { text: // 'Total Shots on Target',value:''},
//   { text: // 'Total Shots off Target',value:''},
//   { text: // 'Total Attacks',value:''},
//   { text: // 'Total Dangerous Attacks',value:''},
//   { text: // 'Total Corners',value:''},
//   { text: // 'Total Possession',value:''},
//   { text: // 'Total Yellow Cards',value:''},
//   { text: // 'Total Red Cards',value:''},
// { text:   // 'Total Goals',value:''},
];

export const minutes = [
  { text: 'One Minute', value: 1 },
  { text: 'Three Minutes', value: 3 },
  { text: 'Five Minutes', value: 5 },
  { text: 'Ten Minutes', value: 10 },
  { text: 'Fifteen Minutes', value: 15 },
]
